In [2]:
import numpy as np
import pandas as pd

In [3]:
#Import ILI Data
FLU = pd.read_csv('WHO_NREVSS_Public_Health_Labs.csv')

In [4]:
FLU.head()

,REGION TYPE,REGION,SEASON_DESCRIPTION,TOTAL SPECIMENS,A (2009 H1N1),A (H3),A (Subtyping not Performed),B,BVic,BYam,H3N2v
0,States,Alabama,Season 2015-16,256,59,16,1,2,2,2,0
1,States,Alaska,Season 2015-16,4691,607,98,0,231,1,2,0
2,States,Arizona,Season 2015-16,2110,762,580,0,13,58,399,0
3,States,Arkansas,Season 2015-16,128,20,8,0,1,12,0,0
4,States,California,Season 2015-16,12820,1462,854,35,775,309,803,0

In [5]:
#Need a flu season variable
#FLU['Season'] = [20000 if x > 26 else 10000 for x in FLU['WEEK']]

KeyError: 'WEEK'

In [41]:
#FLU.sample()

,REGION TYPE,REGION,YEAR,WEEK,TOTAL SPECIMENS,PERCENT POSITIVE,A (2009 H1N1),A (H1),A (H3),A (Subtyping not Performed),A (Unable to Subtype),B,H3N2v,Season
7726,States,Ohio,2013,41,27,0,0,0,0,0,0,0,0,20000

In [42]:
#FLU['Season_Year'] = FLU['Season'] + FLU['YEAR']

In [43]:
#FLU.head()

,REGION TYPE,REGION,YEAR,WEEK,TOTAL SPECIMENS,PERCENT POSITIVE,A (2009 H1N1),A (H1),A (H3),A (Subtyping not Performed),A (Unable to Subtype),B,H3N2v,Season,Season_Year
0,States,Alabama,2010,40,54,0,0,0,0,0,0,0,0,20000,22010
1,States,Alaska,2010,40,40,0,0,0,0,0,0,0,0,20000,22010
2,States,Arizona,2010,40,40,2.5,0,0,1,0,0,0,0,20000,22010
3,States,Arkansas,2010,40,15,0,0,0,0,0,0,0,0,20000,22010
4,States,California,2010,40,183,3.28,2,0,3,0,0,1,0,20000,22010

In [6]:
FLU = FLU.replace('X', np.NaN)

In [7]:
FLU.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
REGION TYPE                    245 non-null object
REGION                         245 non-null object
SEASON_DESCRIPTION             245 non-null object
TOTAL SPECIMENS                244 non-null object
A (2009 H1N1)                  244 non-null object
A (H3)                         244 non-null object
A (Subtyping not Performed)    244 non-null object
B                              244 non-null object
BVic                           244 non-null object
BYam                           244 non-null object
H3N2v                          244 non-null object
dtypes: object(11)
memory usage: 21.2+ KB

FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12011, value = 22010)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12012, value = 22011)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12012, value = 22011)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12013, value = 22012)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12014, value = 22013)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12015, value = 22014)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12016, value = 22015)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12017, value = 22016)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12018, value = 22017)
FLU['Season_Year'] = FLU['Season_Year'].replace(to_replace = 12019, value = 22018)

In [16]:
#convert viruses to int
FLU['A (2009 H1N1)'] = FLU['A (2009 H1N1)'].astype(float)
#FLU['A (H1)'] = FLU['A (H1)'].astype(float)
FLU['A (H3)'] = FLU['A (H3)'].astype(float)
FLU['B'] = FLU['B'].astype(float)
FLU['H3N2v'] = FLU['H3N2v'].astype(float)
FLU['TOTAL SPECIMENS'] = FLU['TOTAL SPECIMENS'].astype(float)
#FLU['PERCENT POSITIVE'] = FLU['PERCENT POSITIVE'].astype(float)
FLU['BVic'] = FLU['BVic'].astype(float)
FLU['BYam'] = FLU['BYam'].astype(float)

In [17]:
FLU_g_s = FLU.drop(columns = ['REGION TYPE'])
FLU_g_s = FLU_g_s.groupby(['SEASON_DESCRIPTION','REGION']).sum()

In [18]:
FLU_Grouped = FLU_g_s.reset_index()

In [19]:
FLU_Grouped.sample(10)

,SEASON_DESCRIPTION,REGION,TOTAL SPECIMENS,A (2009 H1N1),A (H3),B,BVic,BYam,H3N2v
202,Season 2019-20,Connecticut,0.0,0.0,0.0,0.0,0.0,0.0,0.0
135,Season 2017-18,Rhode Island,440.0,13.0,136.0,0.0,1.0,38.0,0.0
167,Season 2018-19,Michigan,1100.0,453.0,359.0,13.0,39.0,24.0,0.0
230,Season 2019-20,Oklahoma,97.0,2.0,1.0,0.0,4.0,0.0,0.0
54,Season 2016-17,Colorado,714.0,3.0,267.0,4.0,31.0,219.0,0.0
189,Season 2018-19,Utah,1194.0,389.0,405.0,2.0,9.0,1.0,0.0
241,Season 2019-20,Washington,107.0,13.0,16.0,1.0,6.0,0.0,0.0
43,Season 2015-16,Vermont,237.0,73.0,48.0,31.0,0.0,1.0,0.0
46,Season 2015-16,West Virginia,549.0,169.0,11.0,96.0,0.0,5.0,0.0
214,Season 2019-20,Maryland,357.0,7.0,6.0,1.0,4.0,1.0,0.0

#Create a function to Make a Season Column
def Season_col(ILI_grouped):
    for i in ILI:
        if ILI['Season_Year'] == 22010:
            return 'Season 2010'
        elif ILI['Season_Year'] == 22011:
            return 'Season 2011-12'
        elif ILI['Season_Year'] == 22012:
            return 'Season 2013-14'

ILI_g = ILI_grouped.apply(function = Season_col(ILI_grouped), axis = 1)

In [20]:
#FLU_Grouped['Season_Year'] = FLU_Grouped['Season_Year'].astype(str)

#FLU_Grouped['Season'] = FLU_Grouped['Season_Year'].replace(to_replace = ['22010','22011','22012','22013','22014','22015','22016', '22017','22018','22019'], value = ['Season 2010','Season 2011-12', 'Season 2012-13', 'Season 2013-14', 'Season 2014-15', 'Season 2015-16','Season 2016-17', 'Season 2017-18', 'Season 2018-19', 'Season 2019'])

KeyError: 'Season_Year'

In [21]:
#FLU_Grouped = FLU_Grouped.drop(columns = ['Season_Year', 'PERCENT POSITIVE'])

In [30]:
FLU_Grouped.to_csv('FLU_Grouped_Public_Health_Labs.csv')

In [27]:
FLU_Grouped.sample(10)

,SEASON_DESCRIPTION,REGION,TOTAL SPECIMENS,A (2009 H1N1),A (H3),B,BVic,BYam,H3N2v
68,Season 2016-17,Massachusetts,485.0,6.0,312.0,1.0,0.0,4.0,0.0
168,Season 2018-19,Minnesota,2961.0,760.0,348.0,0.0,15.0,20.0,0.0
95,Season 2016-17,West Virginia,729.0,2.0,360.0,127.0,0.0,1.0,0.0
161,Season 2018-19,Kansas,415.0,70.0,156.0,0.0,0.0,0.0,0.0
193,Season 2018-19,West Virginia,819.0,307.0,234.0,0.0,3.0,15.0,0.0
207,Season 2019-20,Illinois,375.0,1.0,4.0,52.0,9.0,0.0,0.0
39,Season 2015-16,South Dakota,870.0,260.0,27.0,6.0,47.0,41.0,0.0
8,Season 2015-16,Georgia,1548.0,297.0,32.0,19.0,38.0,41.0,0.0
136,Season 2017-18,South Carolina,876.0,55.0,203.0,15.0,2.0,60.0,0.0
173,Season 2018-19,Nevada,500.0,159.0,105.0,0.0,1.0,1.0,0.0